# Generated by Django 5.1.2 on 2024-11-02 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='user1',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='user2',
        ),
    ]
